[env:lilygo-t-hmi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    pkmurphy/TOTP-Arduino@^1.0.0
build_flags =
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MOSI=13
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=11
    -DTFT_RST=-1
    -DTFT_BL=15
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DSPI_FREQUENCY=40000000
